name: Build and Test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install SDL2
      run: sudo apt install libsdl2-dev

    - uses: actions/checkout@v2

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure --verbose

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upload code coverage to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools cpp-coveralls
        coveralls -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --exclude "venv" --exclude "build/_deps"
